import { useEffect, useState } from 'react'
import { ArrowDownRight, ArrowUpRight, Landmark, Scale } from 'lucide-react'
import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { PageHeader, Empty, Notice, money } from '../components/Ui'
import { api, errorMessage } from '../services/api'
import type { ApiSuccess, Dashboard } from '../types'

const colors = ['#164f3f','#dd694c','#d7a632','#5685a5','#8a6c9f']
export function DashboardPage() {
  const today = new Date().toISOString().slice(0,10); const monthStart = `${today.slice(0,8)}01`
  const [range,setRange]=useState({start_date:monthStart,end_date:today}); const [data,setData]=useState<Dashboard|null>(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(true)
  useEffect(()=>{ setLoading(true); setError(''); api.get<ApiSuccess<Dashboard>>('/dashboard/overview',{params:range}).then(r=>setData(r.data.data)).catch(e=>setError(errorMessage(e))).finally(()=>setLoading(false)) },[range.start_date,range.end_date])
  if (loading) return <div className="grid min-h-[60vh] place-items-center text-sm text-black/50">Montando seu panorama financeiro…</div>
  return <><PageHeader eyebrow="Seu mês em perspectiva" title="Visão geral" description="Números calculados diretamente das suas movimentações, sem dados simulados." action={<div className="card flex gap-2 p-2"><input aria-label="Data inicial" type="date" value={range.start_date} onChange={e=>setRange({...range,start_date:e.target.value})}/><input aria-label="Data final" type="date" value={range.end_date} onChange={e=>setRange({...range,end_date:e.target.value})}/></div>}/>{error && <Notice>{error}</Notice>}{data && <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[
    ['Saldo consolidado',data.consolidated_balance,Landmark,'text-pine'],['Receitas',data.total_income,ArrowUpRight,'text-emerald-600'],['Despesas',data.total_expenses,ArrowDownRight,'text-coral'],['Resultado líquido',data.net_result,Scale,Number(data.net_result)>=0?'text-pine':'text-coral']
  ].map(([label,value,Icon,color])=><div className="card" key={String(label)}><div className="flex items-center justify-between text-xs font-semibold uppercase tracking-wider text-black/45"><span>{String(label)}</span><Icon className={String(color)} size={19}/></div><div className="mt-4 font-display text-2xl font-extrabold">{money(String(value))}</div></div>)}</div>
  <div className="grid gap-5 xl:grid-cols-[1.6fr_1fr]"><section className="card"><h2 className="font-display text-lg font-bold">Fluxo financeiro</h2><p className="text-xs text-black/45">Receitas e despesas por mês</p><div className="mt-5 h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.monthly_flow}><defs><linearGradient id="income" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#164f3f" stopOpacity={.3}/><stop offset="95%" stopColor="#164f3f" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month"/><YAxis/><Tooltip formatter={(v)=>money(String(v))}/><Area type="monotone" dataKey="income" name="Receitas" stroke="#164f3f" fill="url(#income)"/><Area type="monotone" dataKey="expenses" name="Despesas" stroke="#dd694c" fill="transparent"/></AreaChart></ResponsiveContainer></div></section><section className="card"><h2 className="font-display text-lg font-bold">Despesas por categoria</h2>{data.expenses_by_category.length?<div className="h-72"><ResponsiveContainer><PieChart><Pie data={data.expenses_by_category} dataKey="total" nameKey="category_name" innerRadius={55} outerRadius={90}>{data.expenses_by_category.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip formatter={(v)=>money(String(v))}/></PieChart></ResponsiveContainer></div>:<Empty>Nenhuma despesa no período.</Empty>}</section></div>
  <div className="grid gap-5 xl:grid-cols-[1.6fr_1fr]"><section className="card overflow-x-auto"><h2 className="mb-4 font-display text-lg font-bold">Últimas transações</h2>{data.latest_transactions.length?<table className="w-full text-left text-sm"><thead className="text-xs uppercase text-black/40"><tr><th className="pb-3">Descrição</th><th>Data</th><th className="text-right">Valor</th></tr></thead><tbody>{data.latest_transactions.map(t=><tr key={t.id} className="border-t border-black/5"><td className="py-3 font-medium">{t.description}</td><td>{new Date(`${t.date}T12:00:00`).toLocaleDateString('pt-BR')}</td><td className={`text-right font-semibold ${t.type==='INCOME'?'text-emerald-700':'text-coral'}`}>{t.type==='EXPENSE'?'- ':'+ '}{money(t.amount)}</td></tr>)}</tbody></table>:<Empty>Nenhuma transação encontrada.</Empty>}</section><section className="card"><h2 className="mb-4 font-display text-lg font-bold">Alertas</h2>{data.alerts.length?<ul className="space-y-3">{data.alerts.map(a=><li key={a} className="rounded-xl bg-amber-50 p-3 text-sm text-amber-900">{a}</li>)}</ul>:<div className="rounded-xl bg-mint p-4 text-sm text-pine">Tudo tranquilo no período selecionado.</div>}</section></div></div>}</>
}
