import { useEffect, useState, type FormEvent } from 'react'
import { Eye, Pencil, Plus, Trash2, X } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Empty, Notice, PageHeader, money } from '../components/Ui'
import { api, errorMessage } from '../services/api'
import type { ApiSuccess, Transaction } from '../types'

interface Option { id: number; name?: string; nickname?: string }
const blank = { description: '', amount: '', date: new Date().toISOString().slice(0,10), type: 'EXPENSE', category_id: '', bank_account_id: '', origin: 'MANUAL' }

export function TransactionsPage() {
  const [items,setItems]=useState<Transaction[]>([]); const [categories,setCategories]=useState<Option[]>([]); const [accounts,setAccounts]=useState<Option[]>([])
  const [form,setForm]=useState(blank); const [editing,setEditing]=useState<number|null>(null); const [open,setOpen]=useState(false); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
  const [filters,setFilters]=useState({type:'',start_date:'',end_date:''})
  const load=async()=>{ try { const params=Object.fromEntries(Object.entries(filters).filter(([,v])=>v)); const response=await api.get<{data:Transaction[]}>('/transactions',{params:{...params,page:1,page_size:100}}); setItems(response.data.data) } catch(e){setError(errorMessage(e))} }
  useEffect(()=>{ void Promise.all([api.get<ApiSuccess<Option[]>>('/categories'),api.get<ApiSuccess<Option[]>>('/bank-accounts')]).then(([c,a])=>{setCategories(c.data.data);setAccounts(a.data.data)}); void load() },[])
  useEffect(()=>{ void load() },[filters.type,filters.start_date,filters.end_date])
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');const payload={...form,category_id:Number(form.category_id),bank_account_id:form.bank_account_id?Number(form.bank_account_id):null};try{if(editing)await api.put(`/transactions/${editing}`,payload);else await api.post('/transactions',payload);setForm(blank);setEditing(null);setOpen(false);await load()}catch(err){setError(errorMessage(err))}finally{setBusy(false)}}
  const edit=(item:Transaction)=>{setEditing(item.id);setForm({description:item.description,amount:item.amount,date:item.date,type:item.type,category_id:String(item.category_id),bank_account_id:item.bank_account_id?String(item.bank_account_id):'',origin:item.origin});setOpen(true)}
  const remove=async(id:number)=>{if(!window.confirm('Excluir esta transação?'))return;try{await api.delete(`/transactions/${id}`);await load()}catch(e){setError(errorMessage(e))}}
  return <><PageHeader eyebrow="Gestão financeira" title="Transações" description="Registre receitas, despesas e movimentações em dinheiro. Toda validação financeira permanece na API." action={<button className="btn-primary" onClick={()=>{setForm(blank);setEditing(null);setOpen(true)}}><Plus size={17}/>Nova transação</button>}/>
  {error&&<div className="mb-4"><Notice>{error}</Notice></div>}<div className="card mb-5 grid gap-3 sm:grid-cols-3"><select aria-label="Filtrar tipo" value={filters.type} onChange={e=>setFilters({...filters,type:e.target.value})}><option value="">Todos os tipos</option><option value="INCOME">Receitas</option><option value="EXPENSE">Despesas</option></select><input aria-label="Data inicial" type="date" value={filters.start_date} onChange={e=>setFilters({...filters,start_date:e.target.value})}/><input aria-label="Data final" type="date" value={filters.end_date} onChange={e=>setFilters({...filters,end_date:e.target.value})}/></div>
  {open&&<form onSubmit={submit} className="card mb-5"><div className="mb-5 flex items-center justify-between"><h2 className="font-display text-xl font-bold">{editing?'Editar transação':'Nova transação'}</h2><button type="button" onClick={()=>setOpen(false)}><X size={20}/></button></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label className="sm:col-span-2"><span className="label">Descrição</span><input value={form.description} onChange={e=>setForm({...form,description:e.target.value})} required/></label><label><span className="label">Valor</span><input inputMode="decimal" placeholder="0.00" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} required/></label><label><span className="label">Data</span><input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})} required/></label><label><span className="label">Tipo</span><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="EXPENSE">Despesa</option><option value="INCOME">Receita</option></select></label><label><span className="label">Categoria</span><select value={form.category_id} onChange={e=>setForm({...form,category_id:e.target.value})} required><option value="">Selecione</option>{categories.filter(c=>(c as Option & {type?:string}).type===form.type).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label><span className="label">Conta (opcional)</span><select value={form.bank_account_id} onChange={e=>setForm({...form,bank_account_id:e.target.value})}><option value="">Sem conta / dinheiro</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.nickname}</option>)}</select></label><label><span className="label">Origem</span><select value={form.origin} onChange={e=>setForm({...form,origin:e.target.value})}><option value="MANUAL">Manual</option><option value="CASH">Dinheiro</option></select></label></div><button className="btn-primary mt-5" disabled={busy}>{busy?'Salvando…':'Salvar transação'}</button></form>}
  <section className="card overflow-x-auto">{items.length?<table className="w-full min-w-[680px] text-left text-sm"><thead className="text-xs uppercase text-black/40"><tr><th className="pb-3">Descrição</th><th>Data</th><th>Origem</th><th className="text-right">Valor</th><th className="text-right">Ações</th></tr></thead><tbody>{items.map(item=><tr key={item.id} className="border-t border-black/5"><td className="py-3 font-medium">{item.description}</td><td>{new Date(`${item.date}T12:00:00`).toLocaleDateString('pt-BR')}</td><td>{item.origin}</td><td className={`text-right font-semibold ${item.type==='INCOME'?'text-emerald-700':'text-coral'}`}>{item.type==='EXPENSE'?'- ':'+ '}{money(item.amount)}</td><td><div className="flex justify-end gap-1"><Link aria-label="Ver detalhes" className="rounded-lg p-2 hover:bg-black/5" to={`/transactions/${item.id}`}><Eye size={16}/></Link><button aria-label="Editar" className="rounded-lg p-2 hover:bg-black/5" onClick={()=>edit(item)}><Pencil size={16}/></button><button aria-label="Excluir" className="rounded-lg p-2 text-coral hover:bg-red-50" onClick={()=>void remove(item.id)}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table>:<Empty>Nenhuma transação encontrada com esses filtros.</Empty>}</section></>
}
